In [1]:
import numpy as np

In [2]:
myarr = np.array([[3,6,32,7]],  np.int8)

In [3]:
myarr[0,1]

6

In [4]:
myarr.shape

(1, 4)

In [5]:
myarr.dtype

dtype('int8')

In [6]:
myarr[0,1] = 45

In [7]:
myarr

array([[ 3, 45, 32,  7]], dtype=int8)

**Array Creation : Conversion from other python Structures**

In [8]:
listarray = np.array([[1,2,3],[5,6,7],[0,1,2]])

In [9]:
listarray

array([[1, 2, 3],
       [5, 6, 7],
       [0, 1, 2]])

In [10]:
listarray.dtype

dtype('int32')

In [11]:
listarray.shape

(3, 3)

In [12]:
listarray.size

9

In [13]:
np.array({34,23,23})

array({34, 23}, dtype=object)

In [14]:
zeros = np.zeros((2,5))

In [15]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
zeros.dtype

dtype('float64')

In [17]:
range = np.arange(10)

In [18]:
range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
lspace = np.linspace(1,50,10)

In [20]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [21]:
emp = np.empty((4,6))

In [22]:
emp

array([[3.44899859e-307, 1.44635488e-307, 9.34609111e-307,
        2.67024481e-307, 1.33511018e-306, 1.33511969e-306],
       [1.08224926e-312, 2.33644299e-307, 4.67297765e-307,
        2.44774252e-307, 2.33645827e-307, 1.89145877e-307],
       [3.44899689e-307, 5.56295627e-307, 4.45041255e-307,
        4.67293351e-307, 2.33648883e-307, 4.45041255e-307],
       [1.05695337e-307, 3.56036602e-307, 3.33773471e-307,
        4.00541135e-307, 6.89801416e-307, 3.33772792e-307]])

In [23]:
emp_like = np.empty_like(lspace)

In [24]:
emp_like

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [25]:
ide = np.identity(45)

In [26]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [27]:
ide.shape

(45, 45)

In [28]:
arr = np.arange(99)

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [30]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [31]:
arr = arr.ravel()

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [33]:
arr.shape

(99,)

In [34]:
x = [[1,2,3], [4,5,6],[7,1,0]]

In [35]:
ar = np.array(x)

In [36]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [37]:
ar.sum(axis=0)

array([12,  8,  9])

In [38]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [39]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [40]:
ar.flat

In [41]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [42]:
ar.ndim

2

In [43]:
ar.size

9

In [44]:
ar.nbytes

36

In [45]:
one = np.array([1,3,4,56])

In [46]:
one.argmax()

3

In [47]:
one.argmin()

0

In [48]:
one.argsort()

array([0, 1, 2, 3], dtype=int64)

In [49]:
ar.argmin()

8

In [50]:
ar.argmax()

6

In [51]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [52]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

# maths matrix opetion in numpy

In [53]:
ar2= np.array([[9,8,7],
             [6,5,4],
               [3,2,1]])

In [54]:
ar + ar2

array([[10, 10, 10],
       [10, 10, 10],
       [10,  3,  1]])

In [55]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [56]:
ar - ar2

array([[-8, -6, -4],
       [-2,  0,  2],
       [ 4, -1, -1]])

In [57]:
ar *ar2

array([[ 9, 16, 21],
       [24, 25, 24],
       [21,  2,  0]])

In [58]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [59]:
ar.sum()

29

In [60]:
ar.max()

7

In [61]:
ar.min()

0

In [62]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [63]:
type(np.where(ar>5))

tuple

In [64]:
np.count_nonzero(ar)

8

In [65]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [66]:
ar[1,2] =0

In [67]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1], dtype=int64))

In [68]:
import sys

In [69]:
py_ar = [0,4,55,2]

In [70]:
np_ar = np.array(py_ar)

In [71]:
sys.getsizeof(1) * len(py_ar)

112

In [72]:
np_ar.itemsize * np_ar.size

16